modLoader="kotlinforforge"
loaderVersion="[3,)"
license="Creative Commons Attribution-NonCommercial-NoDerivatives 4.0"
issueTrackerURL="https://github.com/ManApart/Lumberjack/issues"

[[mods]]
    modId="unyielding_items"
    version="1.0"
    displayName="Unyielding Items"
	authors="ManApart"
    description='''
   Items never break
    '''
    credits="Items never break"

[[dependencies.unyielding_items]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"